server:
  port: 8001
  servlet:
    context-path: /signer

#eureka:
  #client:
    #service-url:
      #defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-u2d-signer
  profiles:
    active: dev
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
  datasource:
    driverClassName: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/u2d_signer
    username: postgres
    password: 415782

  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yaml